server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9091/eureka/

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  routes:
    delivery-client-server:
      path: /delivery-client-service/**
      serviceId: delivery-client-service    

spring:
  application:
    name: zuul-server 